/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2024-07-10 03:48:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import login.Login;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jstlLogin/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1720572198265L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("login.Login");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("         \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write(" <style>\r\n");
      out.write("   body {\r\n");
      out.write("      margin:0px;\r\n");
      out.write("   }\r\n");
      out.write("   #outer {\r\n");
      out.write("      width:100%;\r\n");
      out.write("      height:45px;\r\n");
      out.write("      background:#5f007f;\r\n");
      out.write("   }\r\n");
      out.write("   #first {\r\n");
      out.write("      width:1100px;\r\n");
      out.write("      height:45px;\r\n");
      out.write("      background:#5f007f;\r\n");
      out.write("      margin:auto;\r\n");
      out.write("   }\r\n");
      out.write("   #first #left {\r\n");
      out.write("      width:1040px;\r\n");
      out.write("      height:45px;\r\n");
      out.write("      display:inline-block;\r\n");
      out.write("      color:white;\r\n");
      out.write("      text-align:center;\r\n");
      out.write("      line-height:45px;\r\n");
      out.write("   }\r\n");
      out.write("   #first #right {\r\n");
      out.write("      width:54px;\r\n");
      out.write("      height:45px;\r\n");
      out.write("      display:inline-block;\r\n");
      out.write("      line-height:45px;\r\n");
      out.write("      color:#eeeeee;\r\n");
      out.write("      font-size:18px;\r\n");
      out.write("   }\r\n");
      out.write("   #second {\r\n");
      out.write("      width:1100px;\r\n");
      out.write("      height:45px;\r\n");
      out.write("      margin:auto;\r\n");
      out.write("      line-height:45px;\r\n");
      out.write("      text-align:right;\r\n");
      out.write("   }\r\n");
      out.write("   #third {\r\n");
      out.write("      width:1100px;\r\n");
      out.write("      height:70px;\r\n");
      out.write("      margin:auto;\r\n");
      out.write("   }\r\n");
      out.write("   #third #left {\r\n");
      out.write("      display:inline-block;\r\n");
      out.write("      width:300px;\r\n");
      out.write("      height:70px;\r\n");
      out.write("      line-height:70px;\r\n");
      out.write("      text-align:left;\r\n");
      out.write("   }\r\n");
      out.write("   #third #left span {\r\n");
      out.write("      font-size:19px;\r\n");
      out.write("      font-weight:900;\r\n");
      out.write("   }\r\n");
      out.write("   #third #left #a1 {\r\n");
      out.write("      color:#5f007f;\r\n");
      out.write("   } \r\n");
      out.write("   #third #left #a2 {\r\n");
      out.write("      color:#dddddd;\r\n");
      out.write("   }\r\n");
      out.write("   #third #left #a3 {\r\n");
      out.write("      color:#dddddd;\r\n");
      out.write("   }\r\n");
      out.write("   #third #left #a3:hover {\r\n");
      out.write("      color:#5f007f;\r\n");
      out.write("   }\r\n");
      out.write("   #third #center {\r\n");
      out.write("      display:inline-block;\r\n");
      out.write("      width:580px;\r\n");
      out.write("      height:70px;\r\n");
      out.write("      line-height:70px;\r\n");
      out.write("      text-align:center;\r\n");
      out.write("   }\r\n");
      out.write("   #third #center #search {\r\n");
      out.write("      width:400px;\r\n");
      out.write("      height:50px;\r\n");
      out.write("      border:1px solid #5f007f;\r\n");
      out.write("      line-height:50px;\r\n");
      out.write("      border-radius:10px;\r\n");
      out.write("   }\r\n");
      out.write("   #third #center #search #text {\r\n");
      out.write("      width:300px;\r\n");
      out.write("      border:none;\r\n");
      out.write("      outline:none;\r\n");
      out.write("   }\r\n");
      out.write("   #third #center #search #xbtn {\r\n");
      out.write("      visibility:hidden;\r\n");
      out.write("   }\r\n");
      out.write("   #third #right {\r\n");
      out.write("      display:inline-block;\r\n");
      out.write("      width:200px;\r\n");
      out.write("      height:70px;\r\n");
      out.write("      line-height:70px;\r\n");
      out.write("      text-align:right;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #fourth {\r\n");
      out.write("      width:1100px;\r\n");
      out.write("      height:50px;\r\n");
      out.write("      margin:auto;\r\n");
      out.write("   }\r\n");
      out.write("   #fourth #menu { /* ul태그 */\r\n");
      out.write("      padding-left:0px;\r\n");
      out.write("   }\r\n");
      out.write("   #fourth #menu li {\r\n");
      out.write("      display:inline-block;\r\n");
      out.write("      width:150px;\r\n");
      out.write("      height:50px;\r\n");
      out.write("      text-align:center;\r\n");
      out.write("      line-height:50px;\r\n");
      out.write("      /*  border:1px solid black; */\r\n");
      out.write("   }\r\n");
      out.write("   #fourth #menu li:first-child {\r\n");
      out.write("      width:240px;\r\n");
      out.write("      text-align:left;\r\n");
      out.write("   }\r\n");
      out.write("   #fourth #menu li:last-child {\r\n");
      out.write("      width:220px;\r\n");
      out.write("      text-align:right;\r\n");
      out.write("   }\r\n");
      out.write("   #fourth #menu li span {\r\n");
      out.write("      border:1px solid #cccccc;\r\n");
      out.write("      padding:3px;\r\n");
      out.write("      padding-left:10px;\r\n");
      out.write("      padding-right:10px;\r\n");
      out.write("      border-radius:12px;\r\n");
      out.write("   }\r\n");
      out.write("   #fourth #menu li span b{\r\n");
      out.write("      color:#5f007f;\r\n");
      out.write("   }\r\n");
      out.write("   #fifth {\r\n");
      out.write("      width:1707px;\r\n");
      out.write("      height:334px;\r\n");
      out.write("      margin:auto;\r\n");
      out.write("   }\r\n");
      out.write("   #sixth {\r\n");
      out.write("      width:1100px;\r\n");
      out.write("      height:60px;\r\n");
      out.write("      margin:auto;\r\n");
      out.write("      text-align:center;\r\n");
      out.write("      margin-top:100px;\r\n");
      out.write("   }\r\n");
      out.write("   #sixth #up {\r\n");
      out.write("      font-size:26px;\r\n");
      out.write("   }\r\n");
      out.write("   #sixth #down {\r\n");
      out.write("      font-size:15px;\r\n");
      out.write("      margin-top:10px;\r\n");
      out.write("      color:#bbbbbb;\r\n");
      out.write("   }\r\n");
      out.write("   #seventh {\r\n");
      out.write("      width:1100px;\r\n");
      out.write("      margin:auto;\r\n");
      out.write("      margin-top:40px;\r\n");
      out.write("   }\r\n");
      out.write("   #seventh button {\r\n");
      out.write("      width:223px; \r\n");
      out.write("      background:white;  \r\n");
      out.write("      border:1px solid #cccccc;\r\n");
      out.write("   }\r\n");
      out.write("   #seventh table #title {\r\n");
      out.write("      width:223px;\r\n");
      out.write("      color:#555555;\r\n");
      out.write("   }\r\n");
      out.write("   #seventh table s {\r\n");
      out.write("      color:#dddddd;\r\n");
      out.write("      font-size:14px;\r\n");
      out.write("   }\r\n");
      out.write("   #seventh table #per {\r\n");
      out.write("      color:red;\r\n");
      out.write("      font-weight:900;\r\n");
      out.write("   }\r\n");
      out.write("   #seventh table #pri {\r\n");
      out.write("      font-weight:900;\r\n");
      out.write("   }\r\n");
      out.write(" </style>\r\n");
      out.write(" <script>\r\n");
      out.write("   function check(my)\r\n");
      out.write("   {\r\n");
      out.write("\t   if(my.value==\"\")\r\n");
      out.write("\t   {\r\n");
      out.write("\t\t   document.getElementById(\"xbtn\").style.visibility=\"hidden\";\r\n");
      out.write("\t   }\t\r\n");
      out.write("\t   else\r\n");
      out.write("\t   {\r\n");
      out.write("\t\t   document.getElementById(\"xbtn\").style.visibility=\"visible\";\r\n");
      out.write("\t   }\t   \r\n");
      out.write("   }\r\n");
      out.write("   function hide()\r\n");
      out.write("   {\r\n");
      out.write("\t   document.getElementById(\"text\").value=\"\";\r\n");
      out.write("\t   document.getElementById(\"xbtn\").style.visibility=\"hidden\";\r\n");
      out.write("   }\r\n");
      out.write(" </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");

    Login.getName(request,session);

      out.write("\r\n");
      out.write("<body> <!-- index.jsp : (웹서버 기본문서 : index.html, index.htm , index.jsp -->\r\n");
      out.write("   <div id=\"outer\">\r\n");
      out.write("     <div id=\"first\">\r\n");
      out.write("       <div id=\"left\"> 지금 가입하고, <b>1만원 할인 쿠폰</b> 받아가세요!</div>\r\n");
      out.write("       <div id=\"right\"> X </div>\r\n");
      out.write("     </div>  \r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"second\">\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("     | 고객센터▼\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"third\">\r\n");
      out.write("     <div id=\"left\"> \r\n");
      out.write("       <img src=\"logo.png\" valign=\"middle\"> <span id=\"a1\">마켓컬리</span> <span id=\"a2\"> | </span> <span id=\"a3\">뷰티컬리</span>\r\n");
      out.write("     </div> <!-- 로고 , 글자  -->\r\n");
      out.write("     <div id=\"center\"> \r\n");
      out.write("       <div id=\"search\">\r\n");
      out.write("          <input type=\"text\" id=\"text\" placeholder=\"검색어를 입력하세요\" onkeyup=\"check(this)\">\r\n");
      out.write("          <img src=\"x.png\" valign=\"middle\" id=\"xbtn\" onclick=\"hide()\">\r\n");
      out.write("          <img src=\"search.png\" valign=\"middle\">\r\n");
      out.write("       </div> \r\n");
      out.write("     </div> <!-- 검색창 -->\r\n");
      out.write("     <div id=\"right\"> <img src=\"icon.png\" valign=\"middle\"> </div> <!-- 링크 아이콘 -->\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"fourth\">\r\n");
      out.write("     <ul id=\"menu\">\r\n");
      out.write("       <li> 카테고리 </li>\r\n");
      out.write("       <li> 신상품 </li>\r\n");
      out.write("       <li> 베스트 </li>\r\n");
      out.write("       <li> 알뜰쇼핑 </li>\r\n");
      out.write("       <li> 특가/혜택 </li>\r\n");
      out.write("       <li> <span> <b>샛별·하루</b>배송안내 </span> </li>\r\n");
      out.write("     </ul>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"fifth\">\r\n");
      out.write("      <img src=\"slide.png\">\r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"sixth\">\r\n");
      out.write("     <div id=\"up\"> 🎂9주년, 이것만 사도 성공👇 > </div> \r\n");
      out.write("     <div id=\"down\"> 지금 인기 있는 벌쓰위크 대표특가를 확인해보세요! </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"seventh\">\r\n");
      out.write("      <table width=\"1100\" align=\"center\">\r\n");
      out.write("        <tr valign=\"top\">\r\n");
      out.write("          <td>\r\n");
      out.write("            <div> <img src=\"p1.png\"> </div>\r\n");
      out.write("            <button>\r\n");
      out.write("              <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"20px\" viewBox=\"0 -960 960 960\" width=\"20px\" fill=\"#5f6368\"><path d=\"M278.4-144q-35.69 0-61.04-25.43Q192-194.86 192-230v-395l-49-119H48v-72h144l59 144h589q14 0 20.5 11.5t.5 23.5L753-406q48 6 79.5 42.94 31.5 36.93 31.5 87.13 0 54.93-38.5 93.43Q787-144 732.22-144q-55.72 0-93.97-38.69Q600-221.39 600-276.13q0-18.87 5-36.87 5-18 16-34l-151-17-121 182q-11.8 18.1-30.4 28.05Q300-144 278.4-144ZM677-413l88-187H280l45 110q8 18 23.39 30.1Q363.78-447.79 384-446l293 33ZM277-216q2.67 0 12-6l101-150q-41-4-75-24.5T264-454v224.39q0 5.61 4 9.61 4 4 9 4Zm455 0q25 0 42.5-17.5T792-276q0-25-17.5-42.5T731.51-336q-24.51 0-42.01 17.5Q672-301 672-275.51q0 24.51 17.5 42.01Q707-216 732-216Zm-55-197-293-33 293 33Z\"/></svg> 담기\r\n");
      out.write("            </button>\r\n");
      out.write("            <div id=\"title\"> [사미헌]갈비탕</div>  \r\n");
      out.write("            <div id=\"oldprice\"> <s>13,000원</s> </div> \r\n");
      out.write("            <div id=\"price\"> <span id=\"per\">10%</span> <span id=\"pri\">11,700원</span> </div>\r\n");
      out.write("          </td>\r\n");
      out.write("          <td>\r\n");
      out.write("            <div> <img src=\"p2.png\"> </div>\r\n");
      out.write("            <button>\r\n");
      out.write("              <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"20px\" viewBox=\"0 -960 960 960\" width=\"20px\" fill=\"#5f6368\"><path d=\"M278.4-144q-35.69 0-61.04-25.43Q192-194.86 192-230v-395l-49-119H48v-72h144l59 144h589q14 0 20.5 11.5t.5 23.5L753-406q48 6 79.5 42.94 31.5 36.93 31.5 87.13 0 54.93-38.5 93.43Q787-144 732.22-144q-55.72 0-93.97-38.69Q600-221.39 600-276.13q0-18.87 5-36.87 5-18 16-34l-151-17-121 182q-11.8 18.1-30.4 28.05Q300-144 278.4-144ZM677-413l88-187H280l45 110q8 18 23.39 30.1Q363.78-447.79 384-446l293 33ZM277-216q2.67 0 12-6l101-150q-41-4-75-24.5T264-454v224.39q0 5.61 4 9.61 4 4 9 4Zm455 0q25 0 42.5-17.5T792-276q0-25-17.5-42.5T731.51-336q-24.51 0-42.01 17.5Q672-301 672-275.51q0 24.51 17.5 42.01Q707-216 732-216Zm-55-197-293-33 293 33Z\"/></svg> 담기\r\n");
      out.write("            </button>\r\n");
      out.write("            <div id=\"title\">[하코야]살얼음 동동 냉메밀 소바2인분</div>   \r\n");
      out.write("            <div id=\"oldprice\"> <s>9,9000원</s> </div> \r\n");
      out.write("            <div id=\"price\"> <span id=\"per\">19%</span> <span id=\"pri\">7,990원</span> </div>\r\n");
      out.write("          </td>\r\n");
      out.write("          <td> \r\n");
      out.write("            <div> <img src=\"p3.png\"> </div>  \r\n");
      out.write("            <button>\r\n");
      out.write("              <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"20px\" viewBox=\"0 -960 960 960\" width=\"20px\" fill=\"#5f6368\"><path d=\"M278.4-144q-35.69 0-61.04-25.43Q192-194.86 192-230v-395l-49-119H48v-72h144l59 144h589q14 0 20.5 11.5t.5 23.5L753-406q48 6 79.5 42.94 31.5 36.93 31.5 87.13 0 54.93-38.5 93.43Q787-144 732.22-144q-55.72 0-93.97-38.69Q600-221.39 600-276.13q0-18.87 5-36.87 5-18 16-34l-151-17-121 182q-11.8 18.1-30.4 28.05Q300-144 278.4-144ZM677-413l88-187H280l45 110q8 18 23.39 30.1Q363.78-447.79 384-446l293 33ZM277-216q2.67 0 12-6l101-150q-41-4-75-24.5T264-454v224.39q0 5.61 4 9.61 4 4 9 4Zm455 0q25 0 42.5-17.5T792-276q0-25-17.5-42.5T731.51-336q-24.51 0-42.01 17.5Q672-301 672-275.51q0 24.51 17.5 42.01Q707-216 732-216Zm-55-197-293-33 293 33Z\"/></svg> 담기\r\n");
      out.write("            </button> \r\n");
      out.write("            <div id=\"title\"> [KF365]훈제오리 150g 2pk</div>\r\n");
      out.write("            <div id=\"oldprice\"> <s>10,500원</s> </div> \r\n");
      out.write("            <div id=\"price\"> <span id=\"per\">33%</span> <span id=\"pri\">6,990원</span> </div>\r\n");
      out.write("          </td>\r\n");
      out.write("          <td>\r\n");
      out.write("            <div> <img src=\"p4.png\"> </div>  \r\n");
      out.write("            <button>\r\n");
      out.write("              <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"20px\" viewBox=\"0 -960 960 960\" width=\"20px\" fill=\"#5f6368\"><path d=\"M278.4-144q-35.69 0-61.04-25.43Q192-194.86 192-230v-395l-49-119H48v-72h144l59 144h589q14 0 20.5 11.5t.5 23.5L753-406q48 6 79.5 42.94 31.5 36.93 31.5 87.13 0 54.93-38.5 93.43Q787-144 732.22-144q-55.72 0-93.97-38.69Q600-221.39 600-276.13q0-18.87 5-36.87 5-18 16-34l-151-17-121 182q-11.8 18.1-30.4 28.05Q300-144 278.4-144ZM677-413l88-187H280l45 110q8 18 23.39 30.1Q363.78-447.79 384-446l293 33ZM277-216q2.67 0 12-6l101-150q-41-4-75-24.5T264-454v224.39q0 5.61 4 9.61 4 4 9 4Zm455 0q25 0 42.5-17.5T792-276q0-25-17.5-42.5T731.51-336q-24.51 0-42.01 17.5Q672-301 672-275.51q0 24.51 17.5 42.01Q707-216 732-216Zm-55-197-293-33 293 33Z\"/></svg> 담기\r\n");
      out.write("            </button> \r\n");
      out.write("            <div id=\"title\">[우주]프리미엄 손질 생새우살 200g(냉동)(26/30사이즈)</div>\r\n");
      out.write("            <div id=\"oldprice\"> <s>8,400원</s> </div> \r\n");
      out.write("            <div id=\"price\"> <span id=\"per\">29%</span> <span id=\"pri\">5,900원</span> </div>\r\n");
      out.write("          </td>\r\n");
      out.write("      </table>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /index.jsp(217,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("     <a href=\"member.jsp\"> 회원가입 </a> | <a href=\"login.jsp\"> 로그인 </a>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /index.jsp(220,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("     <a href=\"memberView.jsp\"> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 </a> | <a href=\"logout.jsp\"> 로그아웃 </a>  \r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
